// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jitxlcptvfifhmniikzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdHhsY3B0dmZpZmhtbmlpa3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzc2MjQsImV4cCI6MjA2OTExMzYyNH0.xYKbOqAHMNql7_IZRw5MTTGXzWj5r_y8U2zWB0tXbok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});